#algo = input('Digite algo: ')
#print('o tipo primitivo desse valor é ', type(algo))
#print('Só tem espaçõs? ', algo.isspace())
#print('é um numero', algo.isnumeric())
#print('é alfabetico', algo.isalpha())
#print('é alfanumerico', algo.isalnum())
#print('esta em maiusculos', algo.isupper())
#print('esta em minusculas', algo.islower())
#print('esta capitalizada', algo.istitle())

a = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(a)}')
print(f'Só tem espaços? {a.isspace()}')
print(f'É um número? {a.isnumeric()}')
print(f'É alfabético? {a.isalpha()}')
print(f'É alfanumérico? {a.isalnum()}')
print(f'Está em maiúsculas? {a.isupper()}')
print(f'Está em minúsculas? {a.islower()}')
print(f'Está capitalizado? {a.istitle()}')
print(f'Está algo? {a.isdigit()}')